### PR TITLE
server: fix error reporting and logic for /keys handler

### PR DESCRIPTION
**Pull request by dev-zero**
restores proper error reporting to include the host dialed, and fixes the tautological comparison `jwks == nil` in the recovery path (which go static analysis would have pointed out) to properly refetch the server config and try again as intended

### CODE REVIEW

**Comment by davidallendj** [comment]
Did you mean the `/keys` handler? I don't see any changes here for `/token`.

**Review by davidallendj — APPROVED** [review]
Looks good, but commit needs to be signed. Would you mind signing so I can merge?

https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by dev-zero** [comment]
@davidallendj yes, you are right. I got an error triggered in `/keys` from `bss` asking for `/tokens` (still have to figure out how that redirect/flow happened). Commit is now signed.

**Comment by davidallendj** [comment]
Thanks! I think I've seen an issue like that before that I thought we fixed. Want to open an issue with the logs so I can take a look at it?

I'll go ahead a merge this and close.

**Pull request merged**
